# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog, QLabel
from PyQt5.QtGui import QIcon, QPixmap
from PyQt5.QtCore import Qt
from keras.models import Sequential, load_model
from keras.layers import Dense, Conv2D, Flatten, MaxPooling2D
import matplotlib.pyplot as plt
from keras.datasets import mnist
from keras.utils.np_utils import to_categorical
from PIL import ImageTk, Image
import numpy as np
import cv2
import os
import sys


class Ui_MainWindow(object):
    def __init__(self):
        self.his = []

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(961, 742)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(20, 0, 841, 511))
        self.photo.setText("")

        self.btn_browse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_browse.setGeometry(QtCore.QRect(180, 600, 101, 31))
        self.btn_browse.setObjectName("btn_browse")
        self.btn_browse.clicked.connect(self.btn_browse_handler)

        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 60, 421, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.hly_showImg = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.hly_showImg.setContentsMargins(0, 0, 0, 0)
        self.hly_showImg.setObjectName("hly_showImg")
        self.hly_showImg.addWidget(self.photo, alignment=Qt.AlignCenter)

        self.btn_run = QtWidgets.QPushButton(self.centralwidget)
        self.btn_run.setGeometry(QtCore.QRect(670, 600, 101, 31))
        self.btn_run.setObjectName("btn_run")
        self.btn_run.clicked.connect(self.btn_run_handler)

        self.listView = QtWidgets.QListWidget(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(510, 60, 421, 511))
        self.listView.setObjectName("listView")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(470, 10, 20, 671))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 961, 21))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_browse.setText(_translate("MainWindow", "Open File"))
        self.btn_run.setText(_translate("MainWindow", "Run"))

    def open_dialog_box(self):
        filename = QFileDialog.getOpenFileName()
        path = filename[0]
        if(path == ''):
            return
        self.show_img(path)
        self.img2arr = self.format_img(path)

    def show_img(self, path):
        pixmap = QPixmap(path)
        pixmap_resize = pixmap.scaled(480, 480, QtCore.Qt.KeepAspectRatio)
        self.photo.setPixmap(pixmap_resize)

    def format_img(self, path=''):
        img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        img = cv2.bitwise_not(img, mask=None)
        img = cv2.resize(img, (28, 28))
        im2arr = np.array(img)
        im2arr = im2arr.reshape(1, 28, 28, 1)
        return im2arr

    def format_img2(self, path=''):
        img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        img = cv2.bitwise_not(img, mask=None)
        img = cv2.resize(img, (28, 28))
        im2arr = np.array(img)
        im2arr = im2arr.reshape(1, 28, 28, 1)
        return im2arr

    def mechine_guess(self, im2arr):
        model = load_model('model2.h5')
        self.result = np.argmax(model.predict(self.img2arr), axis=1)

    def show_his(self):
        self.his.append(str(self.result[0]))
        self.listView.addItems(self.his)
        self.his.clear()

    def btn_browse_handler(self):
        self.open_dialog_box()

    def btn_run_handler(self):
        self.mechine_guess(self.img2arr)
        self.show_his()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
